<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="SDS-V-MUTHU-MAC.local" name="tests.Payments.TEST_payments_using_CCIN_payment" tests="1" failures="1" timestamp="27 Mar 2019 16:47:47 GMT" time="103.526" errors="0">
  <testcase name="User_tries_to_logs_in_as_different_user_Test" time="103.526" classname="tests.Payments.TEST_payments_using_CCIN_payment">
    <failure type="java.lang.AssertionError" message="Something went wrong. Code reached catch block. Please refer stack trace for more info.Expected condition failed: waiting for visibility of element located by By.xpath: //h1[@class=&#039;order-success-title&#039;] (tried for 60 second(s) with 1000 MILLISECONDS interval) expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Something went wrong. Code reached catch block. Please refer stack trace for more info.Expected condition failed: waiting for visibility of element located by By.xpath: //h1[@class='order-success-title'] (tried for 60 second(s) with 1000 MILLISECONDS interval) expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.asserts.Assertion$1.doAssert(Assertion.java:112)
at org.testng.asserts.Assertion.executeAssert(Assertion.java:30)
at org.testng.asserts.Assertion.doAssert(Assertion.java:15)
at org.testng.asserts.Assertion.assertTrue(Assertion.java:109)
at tests.Payments.TEST_payments_using_CCIN_payment.User_tries_to_logs_in_as_different_user_Test(TEST_payments_using_CCIN_payment.java:59)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- User_tries_to_logs_in_as_different_user_Test -->
</testsuite> <!-- tests.Payments.TEST_payments_using_CCIN_payment -->
